---
- name: Install Redis
  ansible.builtin.package:
    name: redis
    state: present

- name: Enable and start Redis
  ansible.builtin.service:
    name: redis
    state: started
    enabled: true

